### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by nicholasmabrams** [ProseMirror/prosemirror-tables#82]
Hi I am trying to use your plugin inside of a product that I am developing, however I get this error on Windows 10 with Node 10.16.0.

```
#> yarn run watch_demo
yarn run v1.17.3
warning package.json: "dependencies" has dependency "prosemirror-example-setup" with range "^1.0.1" that collides with a dependency in "devDependencies" of the same name with version "^1.0.0"
$ rollup -w -c rollup.demo.config.js
rollup v0.49.3
bundles demo.js → demo_bundle.js...
(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
options.entry is now options.input
options.dest is now options.output.file
options.format is now options.output.format
[!] TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '\u0000commonjs-proxy:C:\\Users\\nicholasa\\__source_code\\prosemirror-tables\\node_modules\\orderedmap\\package.json'
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '\u0000commonjs-proxy:C:\\Users\\nicholasa\\__source_code\\prosemirror-tables\\node_modules\\orderedmap\\package.json'
    at Object.readFile (fs.js:296:3)
    at next (C:\Users\nicholasa\__source_code\prosemirror-tables\node_modules\browser-resolve\index.js:98:12)
    at load_shims (C:\Users\nicholasa\__source_code\prosemirror-tables\node_modules\browser-resolve\index.js:116:7)
    at resolve (C:\Users\nicholasa\__source_code\prosemirror-tables\node_modules\browser-resolve\index.js:236:5)
    at C:\Users\nicholasa\__source_code\prosemirror-tables\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:58:5
    at new Promise (<anonymous>)
    at resolveId$1 (C:\Users\nicholasa\__source_code\prosemirror-tables\node_modules\rollup-plugin-node-resolve\dist\rollup-plugin-node-resolve.cjs.js:57:11)
    at promise.then.result (C:\Users\nicholasa\__source_code\prosemirror-tables\node_modules\rollup\dist\rollup.js:1750:32)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
 "dependencies": {
    "prosemirror-example-setup": "^1.0.1",
    "prosemirror-keymap": "^1.0.0",
    "prosemirror-model": "^1.0.0",
    "prosemirror-state": "^1.0.0",
    "prosemirror-transform": "^1.0.0",
    "prosemirror-view": "^1.0.10"
  },
  "devDependencies": {
    "builddocs": "^0.3.0",
    "ist": "^1.0.1",
    "mocha": "^3.4.2",
    "prosemirror-commands": "^1.0.0",
    "prosemirror-example-setup": "^1.0.0",
    "prosemirror-menu": "^1.0.0",
    "prosemirror-schema-basic": "^1.0.0",
    "prosemirror-test-builder": "^1.0.0",
    "rollup": "^0.49.3",
    "rollup-plugin-buble": "^0.15.0",
    "rollup-plugin-commonjs": "^6.0.0",
    "rollup-plugin-node-resolve": "^2.0.0"
  },
```

```
$ yarn -v
1.17.3
```
```
$ npm -v
6.9.0
```

Thank you for your help

**Comment by nicholasmabrams** [comment]
This issue was resolved by downgrading to Node 8. Since there is already a Windows issue which traced back to Node 9 I am closing this.
